cost_function:
  function: mse_cost_function
dataset:
  batch_size: 1
  cutoff: 3.0
  max_samples: null
  path: ../Data/aBN_HSX/nr_atoms_3
  split_ratio: 0.85
device: cuda
exp_path: Example/training_loop_00
model:
  atomic_descriptors:
    avg_num_neighbors: 8
    correlation: 3
    hidden_irreps: 8x0e+8x1o
    interaction_cls: RealAgnosticResidualInteractionBlock
    interaction_cls_first: RealAgnosticResidualInteractionBlock
    max_ell: 3
    nr_bits: 10
    num_elements: 10
    num_interactions: 2
    orbitals:
      1: 13
      2: 13
      3: 13
      4: 13
      5: 13
      6: 13
      7: 13
      8: 13
    radial_mlp:
    - 64
    - 64
    - 64
  avg_num_neighbors: 8
  edge_extraction:
    hidden_dim_matrix_extraction: 900
    hidden_dim_message_passing: 900
    orbitals:
      1: 13
      2: 13
      3: 13
      4: 13
      5: 13
      6: 13
      7: 13
      8: 13
  embedding:
    distance_transform: null
    hidden_irreps: 8x0e+8x1o
    max_ell: 3
    nr_bits: 10
    num_bessel: 8
    num_elements: 10
    num_polynomial_cutoff: 6
    orbitals:
      1: 13
      2: 13
      3: 13
      4: 13
      5: 13
      6: 13
      7: 13
      8: 13
    r_max: 3
    radial_type: bessel
  node_extraction:
    hidden_dim_matrix_extraction: 900
    hidden_dim_message_passing: 900
    orbitals:
      1: 13
      2: 13
      3: 13
      4: 13
      5: 13
      6: 13
      7: 13
      8: 13
  nr_bits: 10
  path_trained_model: null
optimizer:
  lr: 1e-5
  weight_decay: 1e-5
orbitals:
  1: 13
  2: 13
  3: 13
  4: 13
  5: 13
  6: 13
  7: 13
  8: 13
scheduler:
  T_0: 20
  T_mult: 2
  eta_min: 1e-7
trainer:
  filename: best_model.pt
  grad_clip_value: 0.1
  live_plot: true
  num_epochs: 2000
  plot_update_freq: 1
  use_comet: false
