"""
Script to compare the hamiltonians generated by the model with the loss they correspond.
"""
from hforge.utils import load_model_and_dataset_from_directory
from hforge.utils import generate_prediction, get_object_from_module

def main():
    # * Path to the folder where the model and other results are saved.
    directory = r"C:\Users\angel\OneDrive - Universitat de Barcelona\1A. MASTER I\TFM\example_results\usetapprox\example_results_usetapprox_2mp_sharing"
    model_filename = "train_best_model.pt"

    # Load model
    model, history , train_dataset, validation_dataset= load_model_and_dataset_from_directory(directory, model_filename, weights_only=False, return_datasets=True)

    # Load loss function
    # * Change the name of the loss function
    loss_fn_name = "mse_cost_function"
    loss_fn = get_object_from_module(loss_fn_name, "hforge.graph_costfucntion")
    print(loss_fn)
    a

    # Generate predition
    input_graph = train_dataset[0]
    predicted_h = generate_prediction(model, input_graph)


    print(history["train_loss"])


if __name__ == "__main__":
    main()